
name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

env:
  # Java
  JAVA_VERSION: 1.15
  # DockerHub
  DOCKER_HUB_USERNAME: woohobi
  # AWS & Elastic Bean Stalk
  AWS_REGION: ap-northeast-2
  EB_ENVIRONMENT_NAME: Snpservice-env
  EB_APPLICATION_NAME: snpservice-env
  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/docker-compose.yml
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Generate application.yml
      run: echo "${{ secrets.SPRING_CONFIG }}" > ./src/main/resources/application.yml

    # Gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test
      
    - name: Docker build
      run: |
       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker build -t snp-backend .
       docker tag snp-backend jackghl/snp-service:backend
       docker push jackghl/snp-service:backend
   
    - name: Generate docker-compose.yml
      run: echo "${{ secrets.DOCKER_COMPOSE }}" > docker-compose.yml
      
     # Beanstalk
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESSKEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        version_label: "test-back-v${{ github.run_number }}"
        region: ${{ env.AWS_REGION }}
        deployment_package: docker-compose.yml
    
    #remove yml
    - name: Remove application.yml
      run: rm ./src/main/resources/application.yml
    - name: Remove application.yml
      run: rm docker-compose.yml
       
